version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    groups:
      remotion:
        patterns:
          - '@remotion/*'
          - remotion
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
