version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    groups:
      remotion:
        patterns:
          - '@remotion/*'
          - remotion
      react:
        patterns:
          - react
          - react-dom
          - '@types/react'
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
